# Generated by Django 4.1.7 on 2023-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_image_blogs_image_alter_blogs_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('female', 'female'), ('other', 'other')], default='Male', max_length=100),
        ),
    ]
