# Generated by Django 4.1.7 on 2023-04-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_gender_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='user',
        ),
    ]
